[General]

[Rule]

# 你的自定义规则（放最前面）
IP-CIDR,172.22.11.0/24,Proxy,no-resolve
IP-CIDR,172.23.11.0/24,Proxy,no-resolve

# 引入官方规则
INCLUDE,https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/sr_top500_whitelist_ad.conf
