[General]
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local

[Rule]
# 1. 自定义的规则
IP-CIDR,172.22.11.0/24,PROXY
IP-CIDR,172.23.11.0/24,PROXY

# 2. 引入你原本要下载的那个第三方规则/订阅链接
RULE-SET,https://johnshall.github.io/Shadowrocket-ADBlock-Rules-Forever/sr_top500_whitelist_ad.conf,PROXY

# 3. 兜底
FINAL,DIRECT
