
name: Auto Update Shadowrocket Rules

on:
  schedule:
    # 每天凌晨 4 点自动执行一次 (UTC 时间为前一天 20:00)
    - cron: '0 20 * * *'
  workflow_dispatch: # 允许你随时在 GitHub 网页上点击手动触发执行

jobs:
  update:
    runs-size: ubuntu-latest
    steps:
    - name: 签出仓库代码
      uses: actions/checkout@v4

    - name: 赋予脚本执行权限并运行
      run: |
        chmod +x ./update_rules.sh
        ./update_rules.sh

    - name: 检查是否有内容更新并提交到仓库
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add shadow.conf
        # 只有在文件发生实质性改变时才提交，防止空提交报错
        git diff --quiet && git diff --staged --quiet || git commit -m "自动同步最新规则并追加自定义网段"
        git push
